set_property PACKAGE_PIN P17 [get_ports {clk}]
set_property PACKAGE_PIN R15 [get_ports {reset}]

set_property PACKAGE_PIN R11 [get_ports {io_m_key[0]}]
set_property PACKAGE_PIN R17 [get_ports {io_m_key[1]}]
set_property PACKAGE_PIN V1  [get_ports {io_m_key[2]}]
set_property PACKAGE_PIN U4  [get_ports {io_m_key[3]}]

set_property PACKAGE_PIN T5  [get_ports {io_m_switch_0[0]}]
set_property PACKAGE_PIN T3  [get_ports {io_m_switch_0[1]}]
set_property PACKAGE_PIN R3  [get_ports {io_m_switch_0[2]}]
set_property PACKAGE_PIN V4  [get_ports {io_m_switch_0[3]}]
set_property PACKAGE_PIN V5  [get_ports {io_m_switch_0[4]}]
set_property PACKAGE_PIN V2  [get_ports {io_m_switch_0[5]}]
set_property PACKAGE_PIN U2  [get_ports {io_m_switch_0[6]}]
set_property PACKAGE_PIN U3  [get_ports {io_m_switch_0[7]}]

set_property PACKAGE_PIN R1  [get_ports {io_m_switch_1[0]}]
set_property PACKAGE_PIN N4  [get_ports {io_m_switch_1[1]}]
set_property PACKAGE_PIN M4  [get_ports {io_m_switch_1[2]}]
set_property PACKAGE_PIN R2  [get_ports {io_m_switch_1[3]}]
set_property PACKAGE_PIN P2  [get_ports {io_m_switch_1[4]}]
set_property PACKAGE_PIN P3  [get_ports {io_m_switch_1[5]}]
set_property PACKAGE_PIN P4  [get_ports {io_m_switch_1[6]}]
set_property PACKAGE_PIN P5  [get_ports {io_m_switch_1[7]}]

set_property PACKAGE_PIN K3  [get_ports {io_m_led_0[0]}]
set_property PACKAGE_PIN M1  [get_ports {io_m_led_0[1]}]
set_property PACKAGE_PIN L1  [get_ports {io_m_led_0[2]}]
set_property PACKAGE_PIN K6  [get_ports {io_m_led_0[3]}]
set_property PACKAGE_PIN J5  [get_ports {io_m_led_0[4]}]
set_property PACKAGE_PIN H5  [get_ports {io_m_led_0[5]}]
set_property PACKAGE_PIN H6  [get_ports {io_m_led_0[6]}]
set_property PACKAGE_PIN K1  [get_ports {io_m_led_0[7]}]

set_property PACKAGE_PIN K2  [get_ports {io_m_led_1[0]}]
set_property PACKAGE_PIN J2  [get_ports {io_m_led_1[1]}]
set_property PACKAGE_PIN J3  [get_ports {io_m_led_1[2]}]
set_property PACKAGE_PIN H4  [get_ports {io_m_led_1[3]}]
set_property PACKAGE_PIN J4  [get_ports {io_m_led_1[4]}]
set_property PACKAGE_PIN G3  [get_ports {io_m_led_1[5]}]
set_property PACKAGE_PIN G4  [get_ports {io_m_led_1[6]}]
set_property PACKAGE_PIN F6  [get_ports {io_m_led_1[7]}]

set_property PACKAGE_PIN B4  [get_ports {io_m_digit_seg_0[0]}]
set_property PACKAGE_PIN A4  [get_ports {io_m_digit_seg_0[1]}]
set_property PACKAGE_PIN A3  [get_ports {io_m_digit_seg_0[2]}]
set_property PACKAGE_PIN B1  [get_ports {io_m_digit_seg_0[3]}]
set_property PACKAGE_PIN A1  [get_ports {io_m_digit_seg_0[4]}]
set_property PACKAGE_PIN B3  [get_ports {io_m_digit_seg_0[5]}]
set_property PACKAGE_PIN B2  [get_ports {io_m_digit_seg_0[6]}]
set_property PACKAGE_PIN D4  [get_ports {io_m_digit_seg_0[7]}]

set_property PACKAGE_PIN D4  [get_ports {io_m_digit_seg_1[0]}]
set_property PACKAGE_PIN E3  [get_ports {io_m_digit_seg_1[1]}]
set_property PACKAGE_PIN D3  [get_ports {io_m_digit_seg_1[2]}]
set_property PACKAGE_PIN F4  [get_ports {io_m_digit_seg_1[3]}]
set_property PACKAGE_PIN F3  [get_ports {io_m_digit_seg_1[4]}]
set_property PACKAGE_PIN E2  [get_ports {io_m_digit_seg_1[5]}]
set_property PACKAGE_PIN D2  [get_ports {io_m_digit_seg_1[6]}]
set_property PACKAGE_PIN H2  [get_ports {io_m_digit_seg_1[7]}]

set_property PACKAGE_PIN G2  [get_ports {io_m_digit_sel_0[0]}]
set_property PACKAGE_PIN C2  [get_ports {io_m_digit_sel_0[1]}]
set_property PACKAGE_PIN C1  [get_ports {io_m_digit_sel_0[2]}]
set_property PACKAGE_PIN H1  [get_ports {io_m_digit_sel_0[3]}]

set_property PACKAGE_PIN G1  [get_ports {io_m_digit_sel_1[0]}]
set_property PACKAGE_PIN F1  [get_ports {io_m_digit_sel_1[1]}]
set_property PACKAGE_PIN E1  [get_ports {io_m_digit_sel_1[2]}]
set_property PACKAGE_PIN G6  [get_ports {io_m_digit_sel_1[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_m_key[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_m_switch_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_m_switch_1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_m_led_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_m_led_1[*]}]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
